name: SonarCloud analysis

on:
  workflow_run:
    workflows: ["XCode build & test"]
    types:
      - completed
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.cobertura.reportPaths=artifacts/coverage.xml